README.md
=> install info in readme

Dockerfile, docker-compose.yml
Hey hey,
Just tweaking the ports in the DockerFile to be the correct one instead of 80, and changing the "SLOP_INTERFACE" variable in Docker compose file to be a URI.
=> Docker URI Typo

SlopCrew.Server/ServerConnection.cs
=> Check if position and velocity are finite

SlopCrew.Common/Network/Clientbound/ClientBoundSync.cs, SlopCrew.Common/Network/Clientbound/ClientboundPlayerPositionUpdate.cs, SlopCrew.Common/Network/NetworkMessageType.cs, SlopCrew.Common/Network/NetworkPacket.cs, SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/NetworkConnection.cs, SlopCrew.Plugin/Patches/PlayerPatch.cs, SlopCrew.Plugin/PlayerManager.cs, SlopCrew.Server/Server.cs, SlopCrew.Server/ServerConnection.cs
Server
Cleaned up ServerConnection.cs
Optimized BroadcastNewPlayers function 
Added changes needed for position improvements (@prycaustic)
Common
Cleaned up Network Packet
Added ClientboundSync to NetworkMessageType (@prycaustic)
Plugin
Changes to FixedUpdatePlayer for syncing position (still needs a bit of smoothing/tweaking) (@prycaustic)
Added two new functions to AssociatedPlayer used for helping with position syncing (@prycaustic)
Cleaned up NetworkConnection
Cleaned up PlayerManager
Changed messageQueue to be of type Queue (should bring performance improvements but we'll see)
I wanted to separate the commits but github decided to act up even when I was pushing each to specific branches and cherry picking...
Anyway, thanks to Errormine (@prycaustic) for working on the syncing issues. …
=> Various Changes

SlopCrew.Common/Network/NetworkPacket.cs, SlopCrew.Common/SlopCrew.Common.csproj, SlopCrew.Server/SlopWebSocketModule.cs
Closes #12, but that already got closed...
=> Eradicate Newtonsoft.Json

SlopCrew.Common/Network/Clientbound/ClientboundPlayerPositionUpdate.cs, SlopCrew.Common/Network/Serverbound/ServerboundPositionUpdate.cs, SlopCrew.Common/Transform.cs, SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/Patches/PlayerPatch.cs, SlopCrew.Plugin/PlayerManager.cs, SlopCrew.Server/ConnectionState.cs, SlopCrew.Server/Server.cs
=> Rewrite associated player interpolation code

SlopCrew.Common/Network/Clientbound/ClientboundEncounterStart.cs, SlopCrew.Common/Network/Clientbound/ClientboundPlayerScoreUpdate.cs, SlopCrew.Common/Network/NetworkMessageType.cs, SlopCrew.Common/Network/NetworkPacket.cs, SlopCrew.Common/Network/Serverbound/ServerboundEncounterRequest.cs, SlopCrew.Common/Network/Serverbound/ServerboundScoreUpdate.cs, SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/PlayerManager.cs, SlopCrew.Plugin/Plugin.cs, SlopCrew.Plugin/SlopCrew.Plugin.csproj, SlopCrew.Plugin/SlopScoreEncounter.cs, SlopCrew.Server/ConnectionState.cs, SlopCrew.Server/Server.cs
Still needs plenty of work, I started making the SlopScoreEncounter inherit from Reptile.Encounter, but that might wanna be changed. We also probably wanna look into how to use the notification UI for telling players a score battle was requested or something like that
=> Start writing encounter system

SlopCrew.Server/ConnectionState.cs
I FUCKING GOT IT!!!! LETS GOOOO
=> Ignore players connecting with wrong mod version

.github/workflows/plugin-build.yml, .gitignore, build.ps1, gha.ps1
Now people can make sure I didn't RAT them!
=> Build plugin with GitHub Actions

SlopCrew.Common/EncounterConfig.cs, SlopCrew.Common/EncounterType.cs, SlopCrew.Common/Network/Clientbound/ClientboundEncounterRequest.cs, SlopCrew.Common/Network/Clientbound/ClientboundEncounterStart.cs, SlopCrew.Common/Network/Clientbound/ClientboundGraffitiPaint.cs, SlopCrew.Common/Network/NetworkMessageType.cs, SlopCrew.Common/Network/NetworkPacket.cs, SlopCrew.Common/Network/Serverbound/ServerboundEncounterRequest.cs, SlopCrew.Common/Network/Serverbound/ServerboundGraffitiPaint.cs, SlopCrew.NetworkTests/Program.cs, SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/Encounters/SlopComboEncounter.cs, SlopCrew.Plugin/Encounters/SlopEncounter.cs, SlopCrew.Plugin/Encounters/SlopGraffittiEncounter.cs, SlopCrew.Plugin/Patches/GraffitiGamePatch.cs, SlopCrew.Plugin/Patches/GraffitiSpotPatch.cs, SlopCrew.Plugin/Patches/PlayerPatch.cs, SlopCrew.Plugin/PlayerManager.cs, SlopCrew.Plugin/Plugin.cs, SlopCrew.Plugin/SlopCrew.Plugin.csproj, SlopCrew.Plugin/SlopGraffitiSpot.cs, SlopCrew.Plugin/UI/Phone/AppSlopCrew.cs, SlopCrew.Server/ConnectionState.cs
idk why it's not letting me push directly to this branch so here you go
=> WIP Graffiti battle mode, also includes a slight change to encounter configs

SlopCrew.Plugin/Encounters/SlopEncounter.cs
=> Fill boost when starting an encounter

SlopCrew.Plugin/Scripts/Race/CheckpointPin.cs
Instead of having the indicator just there, it gonna have a refreshed animation every 3 seconds
My only concern is whether 3 seconds are long enough, but this can be changed later if necessary anyway
=> Better UI indicator animation on checkpoint

SlopCrew.Server/Race/RacerManager.cs, SlopCrew.Server/SlopWebSocketModule.cs
Title.
Be cautious with `.Remove ` anyway...
=> Fix disconnect not removing a player from a race

SlopCrew.Plugin/Patches/AnimationEventRelayPatch.cs
idk does this fix loc_scuff too?
=> Fix animation exceptions

SlopCrew.Plugin/Extensions/MapControllerExtensions.cs, SlopCrew.Plugin/Patches/LedgeClimbAbilityPatch.cs, SlopCrew.Plugin/Scripts/Race/SimpleCheckpoint.cs
Basically fix this when jumping on a checkpoint that isn't tall
Will update race with better checkpoint placement since the nerf
=> Fix ledge climb on checkpoint

SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Server/ConnectionState.cs
=> Nuke SPECIAL_SKATEBOARD

SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/PlayerManager.cs
Idk if this is a smart way to do this but hey it works! Sadly doesn't help with going sideways on vert ramps lol
=> Sloppy rotating of additional transforms to sync upside down grinds

SlopCrew.Server/Config.cs, SlopCrew.Server/Encounters/StatefulEncounterManager.cs, SlopCrew.Server/Server.cs
Support for local races.
Mostly to fix this issue #88
=> Add support for loading local race configs

SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/Patches/VersionUIHandlerPatch.cs, SlopCrew.Plugin/PlayerManager.cs, SlopCrew.Plugin/Plugin.cs, SlopCrew.Plugin/SlopCrew.Plugin.csproj, SlopCrew.Plugin/UI/InterfaceUtility.cs
Unity made me manually copy a label and an entire DOTween component I had no idea existed
=> Cache nameplate font and star and also use said font in the main menu, for a better preview

SlopCrew.Plugin/AssociatedPlayer.cs, SlopCrew.Plugin/UI/Phone/AppSlopCrew.cs, SlopCrew.Plugin/UI/Phone/AppSpriteSheet.cs, SlopCrew.Plugin/UI/Phone/Encounters/AppEncounters.cs, SlopCrew.Plugin/UI/Phone/Encounters/EncounterButton.cs, SlopCrew.Plugin/UI/Phone/Encounters/EncounterView.cs, SlopCrew.Plugin/UI/Phone/QuickChat/AppQuickChat.cs, SlopCrew.Plugin/UI/Phone/QuickChat/QuickChatButton.cs, SlopCrew.Plugin/UI/Phone/QuickChat/QuickChatView.cs, SlopCrew.Plugin/UI/Phone/SlopCrewButton.cs, SlopCrew.Plugin/UI/Phone/SlopCrewScrollView.cs, SlopCrew.Plugin/UI/QuickChatUtility.cs
=> Fix nameplate, dev star and quick chat text appearing behind graffiti (Also apply code style to app stuff)

docs/FAQ.md
added the latest section from the discord's faq into the docs folder, i'd like to rework and organize it if possible, let me know and i could do it within the same hour
=> updated FAQ to match server
